### ISSUE TITLE
Game Size is bigger than my screen

### ISSUE THREAD

**Issue by FrozenMind** [XYhrihl/2DSpeedEngine#8]
Theres a problem when you try to play this game on a screen thats **not fullHD(1080p)**. It seems like you have fixed values for your screen size, so its out of my screen.

**Comment by XYhrihl** [comment]
I am aware of this Problem.
I plan to make some maps for all common screen sizes and a manual of how to create own maps with the Tiled editor (http://www.mapeditor.org/) as well as a notification when u run a map which is too big for your screen.

**Comment by FrozenMind** [comment]
Closed cause issue is in Todo.

**Comment by XYhrihl** [comment]
I found an even better solution to this problem. 
With the release of alpha_0.3.3 (currently on dev) the maps are scaleable. So you schould be able to play all maps. However if they were made for another screen size they may not look pretty.
